import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Catalog sourced from getmoneythailand.com (Thai top-up storefront), 2026-07-03.
// priceSell is their retail THB price; priceCost assumes a ~7% margin.
const CDN = 'https://www.getmoneythailand.com/images/pictures';
const COST_RATIO = 0.93;

interface SeedProduct {
  name: string;
  sku: string;
  priceSell: number;
}

interface SeedCategory {
  name: string;
  slug: string;
  sortOrder: number;
}

const CATEGORIES: SeedCategory[] = [
  { name: 'FPS', slug: 'fps', sortOrder: 1 },
  { name: 'MOBA', slug: 'moba', sortOrder: 2 },
  { name: 'Battle Royale', slug: 'battle-royale', sortOrder: 3 },
  { name: 'RPG', slug: 'rpg', sortOrder: 4 },
  { name: 'Gift Cards', slug: 'gift-cards', sortOrder: 5 },
];

interface SeedGame {
  name: string;
  slug: string;
  categorySlug?: string;
  description: string;
  descriptionTh: string;
  logoUrl: string;
  sortOrder: number;
  requiresServer?: boolean;
  products: SeedProduct[];
}

const GAMES: SeedGame[] = [
  {
    name: 'Valorant',
    slug: 'valorant',
    categorySlug: 'fps',
    description: 'Valorant Points delivered to your Riot ID in 3–5 minutes.',
    descriptionTh: 'รับ Valorant Points เข้า Riot ID ของคุณภายใน 3–5 นาที',
    logoUrl: `${CDN}/valorant.jpg`,
    sortOrder: 1,
    products: [
      { name: '475 Points', sku: 'VAL-VP-475', priceSell: 127 },
      { name: '1,000 Points', sku: 'VAL-VP-1000', priceSell: 253 },
      { name: '2,050 Points', sku: 'VAL-VP-2050', priceSell: 510 },
      { name: '3,650 Points', sku: 'VAL-VP-3650', priceSell: 899 },
      { name: '4,525 Points', sku: 'VAL-VP-4525', priceSell: 1143 },
      { name: '6,700 Points', sku: 'VAL-VP-6700', priceSell: 1662 },
      { name: '11,000 Points', sku: 'VAL-VP-11000', priceSell: 2565 },
      { name: '22,000 Points', sku: 'VAL-VP-22000', priceSell: 5130 },
    ],
  },
  {
    name: 'Arena of Valor',
    slug: 'rov',
    categorySlug: 'moba',
    description: 'RoV coupons credited to your account instantly.',
    descriptionTh: 'คูปอง RoV เข้าบัญชีของคุณทันที',
    logoUrl: `${CDN}/rov.jpg`,
    sortOrder: 2,
    products: [
      { name: '11 Coupons (10 + 1 bonus)', sku: 'ROV-CP-11', priceSell: 10 },
      { name: '24 Coupons (20 + 4 bonus)', sku: 'ROV-CP-24', priceSell: 20 },
      { name: '60 Coupons (50 + 10 bonus)', sku: 'ROV-CP-60', priceSell: 49 },
      { name: '110 Coupons (83 + 27 bonus)', sku: 'ROV-CP-110', priceSell: 88 },
      { name: '185 Coupons (125 + 60 bonus)', sku: 'ROV-CP-185', priceSell: 146 },
      { name: '370 Coupons (333 + 37 bonus)', sku: 'ROV-CP-370', priceSell: 291 },
      { name: '620 Coupons (590 + 30 bonus)', sku: 'ROV-CP-620', priceSell: 485 },
      { name: '1,240 Coupons (1,178 + 62 bonus)', sku: 'ROV-CP-1240', priceSell: 970 },
      { name: '2,480 Coupons (2,356 + 124 bonus)', sku: 'ROV-CP-2480', priceSell: 1940 },
    ],
  },
  {
    name: 'Free Fire',
    slug: 'freefire',
    categorySlug: 'battle-royale',
    description: 'Diamonds and memberships for Free Fire, delivered instantly.',
    descriptionTh: 'เพชรและแพ็กเกจสมาชิก Free Fire ส่งทันที',
    logoUrl: `${CDN}/freefire.jpg`,
    sortOrder: 3,
    products: [
      { name: '33 Diamonds (30 + 3 bonus)', sku: 'FF-DM-33', priceSell: 10 },
      { name: '68 Diamonds (43 + 25 bonus)', sku: 'FF-DM-68', priceSell: 20 },
      { name: '172 Diamonds (137 + 35 bonus)', sku: 'FF-DM-172', priceSell: 49 },
      { name: '310 Diamonds (231 + 79 bonus)', sku: 'FF-DM-310', priceSell: 88 },
      { name: '517 Diamonds (470 + 47 bonus)', sku: 'FF-DM-517', priceSell: 146 },
      { name: '690 Diamonds (627 + 63 bonus)', sku: 'FF-DM-690', priceSell: 194 },
      { name: '1,052 Diamonds (956 + 96 bonus)', sku: 'FF-DM-1052', priceSell: 291 },
      { name: '1,801 Diamonds (1,637 + 164 bonus)', sku: 'FF-DM-1801', priceSell: 485 },
      { name: '3,698 Diamonds (3,361 + 337 bonus)', sku: 'FF-DM-3698', priceSell: 970 },
      { name: 'Weekly Mini Diamond Membership', sku: 'FF-MEM-WEEK-MINI', priceSell: 33 },
      { name: 'Weekly Diamond Membership', sku: 'FF-MEM-WEEK', priceSell: 65 },
      { name: 'Monthly Diamond Membership', sku: 'FF-MEM-MONTH', priceSell: 292 },
      { name: 'Booyah Pass (BP Card)', sku: 'FF-BP-CARD', priceSell: 88 },
    ],
  },
  {
    name: 'Mobile Legends: Bang Bang',
    slug: 'mobile-legends',
    categorySlug: 'moba',
    description: 'MLBB diamonds credited to your account instantly.',
    descriptionTh: 'เพชร MLBB เข้าบัญชีของคุณทันที',
    logoUrl: `${CDN}/Mobilelegends.jpg`,
    sortOrder: 4,
    products: [
      { name: '100 Diamonds — first top-up (50 + 50)', sku: 'MLBB-FT-100', priceSell: 30 },
      { name: '300 Diamonds — first top-up (150 + 150)', sku: 'MLBB-FT-300', priceSell: 83 },
      { name: '500 Diamonds — first top-up (250 + 250)', sku: 'MLBB-FT-500', priceSell: 131 },
      { name: '1,000 Diamonds — first top-up (500 + 500)', sku: 'MLBB-FT-1000', priceSell: 262 },
      { name: 'Weekly Diamond Pass', sku: 'MLBB-PASS-WEEK', priceSell: 53 },
      { name: '56 Diamonds (51 + 5 bonus)', sku: 'MLBB-DM-56', priceSell: 29 },
      { name: '112 Diamonds (102 + 10 bonus)', sku: 'MLBB-DM-112', priceSell: 56 },
      { name: '223 Diamonds (203 + 20 bonus)', sku: 'MLBB-DM-223', priceSell: 107 },
      { name: '336 Diamonds (303 + 33 bonus)', sku: 'MLBB-DM-336', priceSell: 160 },
      { name: '570 Diamonds (504 + 66 bonus)', sku: 'MLBB-DM-570', priceSell: 265 },
      { name: '1,163 Diamonds (1,007 + 156 bonus)', sku: 'MLBB-DM-1163', priceSell: 515 },
      { name: '2,398 Diamonds (2,015 + 383 bonus)', sku: 'MLBB-DM-2398', priceSell: 1020 },
      { name: '6,042 Diamonds (5,035 + 1,007 bonus)', sku: 'MLBB-DM-6042', priceSell: 2525 },
    ],
  },
  {
    name: 'PUBG Mobile',
    slug: 'pubg-mobile',
    categorySlug: 'battle-royale',
    description: 'Unknown Cash (UC) for PUBG Mobile Global.',
    descriptionTh: 'Unknown Cash (UC) สำหรับ PUBG Mobile Global',
    logoUrl: `${CDN}/pubg_m_global.jpg`,
    sortOrder: 5,
    products: [
      { name: '60 UC', sku: 'PUBG-UC-60', priceSell: 31 },
      { name: '325 UC (300 + 25 bonus)', sku: 'PUBG-UC-325', priceSell: 151 },
      { name: '660 UC (600 + 60 bonus)', sku: 'PUBG-UC-660', priceSell: 301 },
      { name: '1,800 UC (1,500 + 300 bonus)', sku: 'PUBG-UC-1800', priceSell: 751 },
      { name: '3,850 UC (3,000 + 850 bonus)', sku: 'PUBG-UC-3850', priceSell: 1501 },
      { name: '8,100 UC (6,000 + 2,100 bonus)', sku: 'PUBG-UC-8100', priceSell: 3000 },
    ],
  },
  {
    name: 'Genshin Impact',
    slug: 'genshin-impact',
    categorySlug: 'rpg',
    description: 'Genesis Crystals and Welkin Moon for Genshin Impact.',
    descriptionTh: 'Genesis Crystals และ Welkin Moon สำหรับ Genshin Impact',
    logoUrl: `${CDN}/genshin.jpg`,
    sortOrder: 6,
    requiresServer: true,
    products: [
      { name: 'Blessing of the Welkin Moon', sku: 'GI-WELKIN', priceSell: 144 },
      { name: '60 Genesis Crystals', sku: 'GI-GC-60', priceSell: 28 },
      { name: '330 Genesis Crystals (300 + 30 bonus)', sku: 'GI-GC-330', priceSell: 144 },
      { name: '1,090 Genesis Crystals (980 + 110 bonus)', sku: 'GI-GC-1090', priceSell: 440 },
      { name: '2,240 Genesis Crystals (1,980 + 260 bonus)', sku: 'GI-GC-2240', priceSell: 880 },
      { name: '3,880 Genesis Crystals (3,280 + 600 bonus)', sku: 'GI-GC-3880', priceSell: 1440 },
      { name: '8,080 Genesis Crystals (6,480 + 1,600 bonus)', sku: 'GI-GC-8080', priceSell: 2960 },
    ],
  },
  {
    name: 'Honkai: Star Rail',
    slug: 'honkai-star-rail',
    categorySlug: 'rpg',
    description: 'Oneiric Shards and Express Supply Pass for Honkai: Star Rail.',
    descriptionTh: 'Oneiric Shards และ Express Supply Pass สำหรับ Honkai: Star Rail',
    logoUrl: `${CDN}/honkaistarrail.jpg`,
    sortOrder: 7,
    requiresServer: true,
    products: [
      { name: 'Express Supply Pass', sku: 'HSR-PASS', priceSell: 155 },
      { name: '60 Oneiric Shards', sku: 'HSR-OS-60', priceSell: 31 },
      { name: '330 Oneiric Shards (300 + 30 bonus)', sku: 'HSR-OS-330', priceSell: 155 },
      { name: '1,090 Oneiric Shards (980 + 110 bonus)', sku: 'HSR-OS-1090', priceSell: 475 },
      { name: '2,240 Oneiric Shards (1,980 + 260 bonus)', sku: 'HSR-OS-2240', priceSell: 945 },
      { name: '3,880 Oneiric Shards (3,280 + 600 bonus)', sku: 'HSR-OS-3880', priceSell: 1530 },
      { name: '8,080 Oneiric Shards (6,480 + 1,600 bonus)', sku: 'HSR-OS-8080', priceSell: 3150 },
    ],
  },
  {
    name: 'Wuthering Waves',
    slug: 'wuthering-waves',
    categorySlug: 'rpg',
    description: 'Lunite and Lunite Subscription for Wuthering Waves.',
    descriptionTh: 'Lunite และแพ็กเกจรายเดือน Lunite สำหรับ Wuthering Waves',
    logoUrl: `${CDN}/wuthering-wave.jpg`,
    sortOrder: 8,
    requiresServer: true,
    products: [
      { name: 'Lunite Subscription', sku: 'WUWA-SUB', priceSell: 144 },
      { name: '60 Lunite', sku: 'WUWA-LUN-60', priceSell: 28 },
      { name: '330 Lunite (300 + 30 bonus)', sku: 'WUWA-LUN-330', priceSell: 144 },
      { name: '1,090 Lunite (980 + 110 bonus)', sku: 'WUWA-LUN-1090', priceSell: 440 },
      { name: '2,240 Lunite (1,980 + 260 bonus)', sku: 'WUWA-LUN-2240', priceSell: 880 },
      { name: '3,880 Lunite (3,280 + 600 bonus)', sku: 'WUWA-LUN-3880', priceSell: 1440 },
      { name: '8,080 Lunite (6,480 + 1,600 bonus)', sku: 'WUWA-LUN-8080', priceSell: 2960 },
    ],
  },
  {
    name: 'Honor of Kings',
    slug: 'honor-of-kings',
    categorySlug: 'moba',
    description: 'Tokens for Honor of Kings (Global), credited instantly.',
    descriptionTh: 'โทเคนสำหรับ Honor of Kings (Global) เข้าบัญชีทันที',
    logoUrl: `${CDN}/honorofkings.jpg`,
    sortOrder: 9,
    products: [
      { name: '80 Tokens', sku: 'HOK-TK-80', priceSell: 31 },
      { name: '400 Tokens', sku: 'HOK-TK-400', priceSell: 150 },
      { name: '560 Tokens', sku: 'HOK-TK-560', priceSell: 215 },
      { name: '830 Tokens (800 + 30 bonus)', sku: 'HOK-TK-830', priceSell: 302 },
      { name: '2,508 Tokens (2,400 + 108 bonus)', sku: 'HOK-TK-2508', priceSell: 870 },
      { name: '4,180 Tokens (4,000 + 180 bonus)', sku: 'HOK-TK-4180', priceSell: 1467 },
    ],
  },
  {
    name: 'Zenless Zone Zero',
    slug: 'zenless-zone-zero',
    categorySlug: 'rpg',
    description: 'Monochrome and Inter-Knot Membership for Zenless Zone Zero.',
    descriptionTh: 'Monochrome และ Inter-Knot Membership สำหรับ Zenless Zone Zero',
    logoUrl: `${CDN}/zzz.jpg`,
    sortOrder: 10,
    requiresServer: true,
    products: [
      { name: 'Inter-Knot Membership', sku: 'ZZZ-PASS', priceSell: 155 },
      { name: '60 Monochrome', sku: 'ZZZ-MONO-60', priceSell: 31 },
      { name: '330 Monochrome (300 + 30 bonus)', sku: 'ZZZ-MONO-330', priceSell: 155 },
      { name: '1,090 Monochrome (980 + 110 bonus)', sku: 'ZZZ-MONO-1090', priceSell: 475 },
      { name: '2,240 Monochrome (1,980 + 260 bonus)', sku: 'ZZZ-MONO-2240', priceSell: 945 },
      { name: '3,880 Monochrome (3,280 + 600 bonus)', sku: 'ZZZ-MONO-3880', priceSell: 1530 },
      { name: '8,080 Monochrome (6,480 + 1,600 bonus)', sku: 'ZZZ-MONO-8080', priceSell: 3150 },
    ],
  },

  {
    name: 'League of Legends (LOL PC)',
    slug: 'lol-pc',
    categorySlug: 'moba',
    description: 'League of Legends (LOL PC) top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม League of Legends (LOL PC) ราคาถูก โอนไว',
    logoUrl: `${CDN}/lol-pc.jpg`,
    sortOrder: 11,
    products: [
      { name: '575 RP', sku: 'LOLPC-01', priceSell: 126 },
      { name: '1,275 RP (+105 RP bonus (total 1,380 RP))', sku: 'LOLPC-02', priceSell: 280 },
      { name: '2,525 RP (+275 RP bonus (total 2,800 RP))', sku: 'LOLPC-03', priceSell: 539 },
      { name: '4,025 RP (+475 RP bonus (total 4,500 RP))', sku: 'LOLPC-04', priceSell: 859 },
      { name: '5,750 RP (+750 RP bonus (total 6,500 RP))', sku: 'LOLPC-05', priceSell: 1209 },
      { name: '11,525 RP (+1,975 RP bonus (total 13,500 RP))', sku: 'LOLPC-06', priceSell: 2469 },
    ],
  },

  {
    name: 'Sword of Justice SEA',
    slug: 'sword-of-justice',
    categorySlug: 'rpg',
    description: 'Sword of Justice SEA top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Sword of Justice SEA ราคาถูก โอนไว',
    logoUrl: `${CDN}/sword-of-justice.jpg`,
    sortOrder: 12,
    products: [
      { name: 'Exquisite Treasure (สมบัติของล้ำค่าอันงดงาม)', sku: 'SWORDOFJUSTICE-01', priceSell: 10 },
      { name: 'Monthly Pass (บัตรรายเดือน)', sku: 'SWORDOFJUSTICE-02', priceSell: 156 },
      { name: 'Basic Battle Pass (คำสั่งรบพื้นฐาน)', sku: 'SWORDOFJUSTICE-03', priceSell: 311 },
      { name: 'Upgrade Battle Pass Basic to Advanced', sku: 'SWORDOFJUSTICE-04', priceSell: 460 },
      { name: 'Advanced Battle Pass (คำสั่งรบขั้นสูง)', sku: 'SWORDOFJUSTICE-05', priceSell: 703 },
      { name: '60 Ornate Jade (First top-up bonus: +5 Ornate Jade)', sku: 'SWORDOFJUSTICE-06', priceSell: 37 },
      { name: '300 Ornate Jade (First top-up bonus: +30+24 Ornate Jade)', sku: 'SWORDOFJUSTICE-07', priceSell: 161 },
      { name: '980 Ornate Jade (First top-up bonus: +120+78 Ornate Jade)', sku: 'SWORDOFJUSTICE-08', priceSell: 488 },
      { name: '1,980 Ornate Jade (First top-up bonus: +288+157 Ornate Jade)', sku: 'SWORDOFJUSTICE-09', priceSell: 985 },
      { name: '3,280 Ornate Jade (First top-up bonus: +528+262 Ornate Jade)', sku: 'SWORDOFJUSTICE-10', priceSell: 1592 },
      { name: '6,480 Ornate Jade (First top-up bonus: +1296+519 Ornate Jade)', sku: 'SWORDOFJUSTICE-11', priceSell: 3082 },
    ],
  },

  {
    name: 'Roblox (ID-Pass)',
    slug: 'roblox',
    categorySlug: undefined,
    description: 'Roblox (ID-Pass) top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Roblox (ID-Pass) ราคาถูก โอนไว',
    logoUrl: `${CDN}/roblox.jpg`,
    sortOrder: 13,
    products: [
      { name: '40 Robux (normally 20 THB)', sku: 'ROBLOX-01', priceSell: 17 },
      { name: '80 Robux (normally 40 THB)', sku: 'ROBLOX-02', priceSell: 37 },
      { name: '500 Robux (normally 200 THB)', sku: 'ROBLOX-03', priceSell: 163 },
      { name: '1,000 Robux (normally 400 THB)', sku: 'ROBLOX-04', priceSell: 310 },
      { name: '2,000 Robux (normally 800 THB)', sku: 'ROBLOX-05', priceSell: 615 },
      { name: '4,500 Robux (normally 2,000 THB)', sku: 'ROBLOX-06', priceSell: 1420 },
      { name: '10,000 Robux (normally 4,000 THB)', sku: 'ROBLOX-07', priceSell: 3145 },
      { name: '22,500 Robux (normally 8,000 THB)', sku: 'ROBLOX-08', priceSell: 6357 },
    ],
  },

  {
    name: 'Dragon Traveler (ID-Pass)',
    slug: 'dragon-traveler',
    categorySlug: undefined,
    description: 'Dragon Traveler (ID-Pass) top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Dragon Traveler (ID-Pass) ราคาถูก โอนไว',
    logoUrl: `${CDN}/dragon-traveler.jpg`,
    sortOrder: 14,
    products: [
      { name: 'Package (in-game price 29 THB)', sku: 'DRAGONTRAVELER-01', priceSell: 29 },
      { name: 'Package (in-game price 59 THB)', sku: 'DRAGONTRAVELER-02', priceSell: 60 },
      { name: 'Package (in-game price 85 THB)', sku: 'DRAGONTRAVELER-03', priceSell: 88 },
      { name: 'Package (in-game price 119 THB)', sku: 'DRAGONTRAVELER-04', priceSell: 120 },
      { name: 'Package (in-game price 145 THB)', sku: 'DRAGONTRAVELER-05', priceSell: 148 },
      { name: 'Package (in-game price 239 THB)', sku: 'DRAGONTRAVELER-06', priceSell: 229 },
      { name: 'Package (in-game price 325 THB)', sku: 'DRAGONTRAVELER-07', priceSell: 319 },
      { name: 'Package (in-game price 419 THB)', sku: 'DRAGONTRAVELER-08', priceSell: 408 },
      { name: 'Package (in-game price 470 THB)', sku: 'DRAGONTRAVELER-09', priceSell: 450 },
      { name: 'Package (in-game price 610 THB)', sku: 'DRAGONTRAVELER-10', priceSell: 581 },
      { name: 'Package (in-game price 779 THB)', sku: 'DRAGONTRAVELER-11', priceSell: 747 },
      { name: 'Package (in-game price 800 THB)', sku: 'DRAGONTRAVELER-12', priceSell: 780 },
      { name: 'Package (in-game price 940 THB)', sku: 'DRAGONTRAVELER-13', priceSell: 916 },
      { name: 'Package (in-game price 1,200 THB)', sku: 'DRAGONTRAVELER-14', priceSell: 1147 },
      { name: 'Package (in-game price 1,400 THB)', sku: 'DRAGONTRAVELER-15', priceSell: 1357 },
      { name: 'Package (in-game price 1,550 THB)', sku: 'DRAGONTRAVELER-16', priceSell: 1430 },
      { name: 'Package (in-game price 3,000 THB)', sku: 'DRAGONTRAVELER-17', priceSell: 2860 },
    ],
  },

  {
    name: 'Teamfight Tactics Mobile',
    slug: 'teamfight-tactics',
    categorySlug: 'moba',
    description: 'Teamfight Tactics Mobile top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Teamfight Tactics Mobile ราคาถูก โอนไว',
    logoUrl: `${CDN}/teamfight-tactics.jpg`,
    sortOrder: 15,
    products: [
      { name: '575 TFT Coin', sku: 'TEAMFIGHTTACTI-01', priceSell: 126 },
      { name: '1,275 TFT Coin (+105 TFT Coin bonus (total 1,380))', sku: 'TEAMFIGHTTACTI-02', priceSell: 280 },
      { name: '2,525 TFT Coin (+275 TFT Coin bonus (total 2,800))', sku: 'TEAMFIGHTTACTI-03', priceSell: 539 },
      { name: '4,025 TFT Coin (+475 TFT Coin bonus (total 4,500))', sku: 'TEAMFIGHTTACTI-04', priceSell: 859 },
      { name: '5,750 TFT Coin (+750 TFT Coin bonus (total 6,500))', sku: 'TEAMFIGHTTACTI-05', priceSell: 1209 },
      { name: '11,525 TFT Coin (+1,975 TFT Coin bonus (total 13,500))', sku: 'TEAMFIGHTTACTI-06', priceSell: 2469 },
    ],
  },

  {
    name: 'League of Legends: Wild Rift',
    slug: 'lol-wild-rift',
    categorySlug: 'moba',
    description: 'League of Legends: Wild Rift top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม League of Legends: Wild Rift ราคาถูก โอนไว',
    logoUrl: `${CDN}/lol-wild-rift.jpg`,
    sortOrder: 16,
    products: [
      { name: '425 Wild Cores', sku: 'LOLWILDRIFT-01', priceSell: 145 },
      { name: '1,000 Wild Cores', sku: 'LOLWILDRIFT-02', priceSell: 330 },
      { name: '1,850 Wild Cores', sku: 'LOLWILDRIFT-03', priceSell: 585 },
      { name: '3,275 Wild Cores', sku: 'LOLWILDRIFT-04', priceSell: 1019 },
      { name: '4,800 Wild Cores', sku: 'LOLWILDRIFT-05', priceSell: 1449 },
      { name: '10,000 Wild Cores', sku: 'LOLWILDRIFT-06', priceSell: 2899 },
    ],
  },

  {
    name: 'Legends of Runeterra',
    slug: 'legends-of-runeterra',
    categorySlug: undefined,
    description: 'Legends of Runeterra top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Legends of Runeterra ราคาถูก โอนไว',
    logoUrl: `${CDN}/legends-of-runeterra.jpg`,
    sortOrder: 17,
    products: [
      { name: '475 Coins', sku: 'LEGENDSOFRUNET-01', priceSell: 145 },
      { name: '1,000 Coins', sku: 'LEGENDSOFRUNET-02', priceSell: 291 },
      { name: '2,050 Coins', sku: 'LEGENDSOFRUNET-03', priceSell: 585 },
      { name: '3,650 Coins', sku: 'LEGENDSOFRUNET-04', priceSell: 1019 },
      { name: '5,350 Coins', sku: 'LEGENDSOFRUNET-05', priceSell: 1409 },
      { name: '11,000 Coins', sku: 'LEGENDSOFRUNET-06', priceSell: 2799 },
    ],
  },

  {
    name: 'Haikyu Fly High',
    slug: 'haikyu-fly-high',
    categorySlug: undefined,
    description: 'Haikyu Fly High top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Haikyu Fly High ราคาถูก โอนไว',
    logoUrl: `${CDN}/haikyu-fly-high.jpg`,
    sortOrder: 18,
    products: [
      { name: '60 Star Gems (First top-up bonus: +60 Star Gems)', sku: 'HAIKYUFLYHIGH-01', priceSell: 33 },
      { name: '300 Star Gems (First top-up bonus: +300 Star Gems)', sku: 'HAIKYUFLYHIGH-02', priceSell: 161 },
      { name: '980 Star Gems (First top-up bonus: +980 Star Gems)', sku: 'HAIKYUFLYHIGH-03', priceSell: 481 },
      { name: '1,980 Star Gems (First top-up bonus: +1,980 Star Gems)', sku: 'HAIKYUFLYHIGH-04', priceSell: 961 },
      { name: '3,280 Star Gems (First top-up bonus: +3,280 Star Gems)', sku: 'HAIKYUFLYHIGH-05', priceSell: 1602 },
      { name: '6,480 Star Gems (First top-up bonus: +6,480 Star Gems)', sku: 'HAIKYUFLYHIGH-06', priceSell: 3111 },
    ],
  },

  {
    name: 'Call of Duty Mobile (Garena)',
    slug: 'cod-mobile-garena',
    categorySlug: 'fps',
    description: 'Call of Duty Mobile (Garena) top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Call of Duty Mobile (Garena) ราคาถูก โอนไว',
    logoUrl: `${CDN}/cod-mobile-garena.jpg`,
    sortOrder: 19,
    products: [
      { name: '44 CP (+4 CP bonus (total 48 CP))', sku: 'CODMOBILEGAREN-01', priceSell: 20 },
      { name: '108 CP (+18 CP bonus (total 126 CP))', sku: 'CODMOBILEGAREN-02', priceSell: 49 },
      { name: '194 CP (+33 CP bonus (total 227 CP))', sku: 'CODMOBILEGAREN-03', priceSell: 87 },
      { name: '237 CP (+15 CP bonus (total 252 CP))', sku: 'CODMOBILEGAREN-04', priceSell: 96 },
      { name: '324 CP (+54 CP bonus (total 378 CP))', sku: 'CODMOBILEGAREN-05', priceSell: 145 },
      { name: '648 CP (+144 CP bonus (total 792 CP))', sku: 'CODMOBILEGAREN-06', priceSell: 290 },
      { name: '1,080 CP (+360 CP bonus (total 1,440 CP))', sku: 'CODMOBILEGAREN-07', priceSell: 476 },
      { name: '2,160 CP (+840 CP bonus (total 3,000 CP))', sku: 'CODMOBILEGAREN-08', priceSell: 949 },
      { name: '4,320 CP (+1,680 CP bonus (total 6,000 CP))', sku: 'CODMOBILEGAREN-09', priceSell: 1895 },
      { name: '6,480 CP (+2,520 CP bonus (total 9,000 CP))', sku: 'CODMOBILEGAREN-10', priceSell: 2840 },
      { name: '8,640 CP (+3,360 CP bonus (total 12,000 CP))', sku: 'CODMOBILEGAREN-11', priceSell: 3785 },
      { name: '10,800 CP (+4,200 CP bonus (total 15,000 CP))', sku: 'CODMOBILEGAREN-12', priceSell: 4725 },
    ],
  },

  {
    name: 'Garena Undawn',
    slug: 'garena-undawn',
    categorySlug: undefined,
    description: 'Garena Undawn top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Garena Undawn ราคาถูก โอนไว',
    logoUrl: `${CDN}/garena-undawn.jpg`,
    sortOrder: 20,
    products: [
      { name: '50 RC (+5 RC bonus (total 55 RC))', sku: 'GARENAUNDAWN-01', priceSell: 20 },
      { name: '125 RC (+13 RC bonus (total 138 RC))', sku: 'GARENAUNDAWN-02', priceSell: 49 },
      { name: '230 RC (+23 RC bonus (total 253 RC))', sku: 'GARENAUNDAWN-03', priceSell: 88 },
      { name: '400 RC (+40 RC bonus (total 440 RC))', sku: 'GARENAUNDAWN-04', priceSell: 146 },
      { name: '800 RC (+80 RC bonus (total 880 RC))', sku: 'GARENAUNDAWN-05', priceSell: 291 },
      { name: '1,350 RC (+135 RC bonus (total 1,485 RC))', sku: 'GARENAUNDAWN-06', priceSell: 485 },
      { name: '2,700 RC (+270 RC bonus (total 2,970 RC))', sku: 'GARENAUNDAWN-07', priceSell: 970 },
      { name: '4,100 RC (+410 RC bonus (total 4,510 RC))', sku: 'GARENAUNDAWN-08', priceSell: 1455 },
      { name: '5,500 RC (+550 RC bonus (total 6,050 RC))', sku: 'GARENAUNDAWN-09', priceSell: 1940 },
      { name: '8,380 RC (+838 RC bonus (total 9,218 RC))', sku: 'GARENAUNDAWN-10', priceSell: 2910 },
      { name: '14,220 RC (+1,422 RC bonus (total 15,642 RC))', sku: 'GARENAUNDAWN-11', priceSell: 4850 },
    ],
  },

  {
    name: 'Delta Force (Garena)',
    slug: 'delta-force-garena',
    categorySlug: 'fps',
    description: 'Delta Force (Garena) top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Delta Force (Garena) ราคาถูก โอนไว',
    logoUrl: `${CDN}/delta-force-garena.jpg`,
    sortOrder: 21,
    products: [
      { name: '18 Delta Coins (+1 Delta Coin bonus (total 19))', sku: 'DELTAFORCEGARE-01', priceSell: 10 },
      { name: '30 Delta Coins (+2 Delta Coins bonus (total 32))', sku: 'DELTAFORCEGARE-02', priceSell: 17 },
      { name: '60 Delta Coins (+3 Delta Coins bonus (total 63))', sku: 'DELTAFORCEGARE-03', priceSell: 34 },
      { name: '300 Delta Coins (+36 Delta Coins bonus (total 336))', sku: 'DELTAFORCEGARE-04', priceSell: 170 },
      { name: '420 Delta Coins (+62 Delta Coins bonus (total 482))', sku: 'DELTAFORCEGARE-05', priceSell: 238 },
      { name: '680 Delta Coins (+105 Delta Coins bonus (total 785))', sku: 'DELTAFORCEGARE-06', priceSell: 335 },
      { name: '1,280 Delta Coins (+264 Delta Coins bonus (total 1,544))', sku: 'DELTAFORCEGARE-07', priceSell: 669 },
      { name: '1,680 Delta Coins (+385 Delta Coins bonus (total 2,065))', sku: 'DELTAFORCEGARE-08', priceSell: 836 },
      { name: '3,280 Delta Coins (+834 Delta Coins bonus (total 4,114))', sku: 'DELTAFORCEGARE-09', priceSell: 1645 },
      { name: '6,480 Delta Coins (+1,944 Delta Coins bonus (total 8,424))', sku: 'DELTAFORCEGARE-10', priceSell: 3273 },
      { name: '12,960 Delta Coins (+3,888 Delta Coins bonus (total 16,848))', sku: 'DELTAFORCEGARE-11', priceSell: 6540 },
      { name: '19,440 Delta Coins (+5,832 Delta Coins bonus (total 25,272))', sku: 'DELTAFORCEGARE-12', priceSell: 9828 },
    ],
  },

  {
    name: 'Where Winds Meet',
    slug: 'where-winds-meet',
    categorySlug: 'rpg',
    description: 'Where Winds Meet top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Where Winds Meet ราคาถูก โอนไว',
    logoUrl: `${CDN}/where-winds-meet.jpg`,
    sortOrder: 22,
    products: [
      { name: 'Monthly Pass', sku: 'WHEREWINDSMEET-01', priceSell: 157 },
      { name: 'Elite Battle Pass', sku: 'WHEREWINDSMEET-02', priceSell: 310 },
      { name: 'Premium Battle Pass', sku: 'WHEREWINDSMEET-03', priceSell: 617 },
      { name: '60 Echo Beads (First top-up bonus: +60 Green Jade)', sku: 'WHEREWINDSMEET-04', priceSell: 35 },
      { name: '180 Echo Beads (First top-up bonus: +180 Green Jade)', sku: 'WHEREWINDSMEET-05', priceSell: 99 },
      { name: '300 Echo Beads', sku: 'WHEREWINDSMEET-06', priceSell: 157 },
      { name: '600 Echo Beads', sku: 'WHEREWINDSMEET-07', priceSell: 310 },
      { name: '900 Echo Beads', sku: 'WHEREWINDSMEET-08', priceSell: 475 },
      { name: '1,800 Echo Beads', sku: 'WHEREWINDSMEET-09', priceSell: 940 },
      { name: '3,000 Echo Beads', sku: 'WHEREWINDSMEET-10', priceSell: 1550 },
      { name: '6,000 Echo Beads', sku: 'WHEREWINDSMEET-11', priceSell: 3082 },
      { name: '12,000 Echo Beads', sku: 'WHEREWINDSMEET-12', priceSell: 6155 },
    ],
  },

  {
    name: 'Blood Strike',
    slug: 'blood-strike',
    categorySlug: 'fps',
    description: 'Blood Strike top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Blood Strike ราคาถูก โอนไว',
    logoUrl: `${CDN}/blood-strike.jpg`,
    sortOrder: 23,
    products: [
      { name: '100 Golds (+5 Golds bonus (total 105))', sku: 'BLOODSTRIKE-01', priceSell: 28 },
      { name: '300 Golds (+10 Golds bonus (total 310))', sku: 'BLOODSTRIKE-02', priceSell: 84 },
      { name: '500 Golds (+40 Golds bonus (total 540))', sku: 'BLOODSTRIKE-03', priceSell: 140 },
      { name: '1,000 Golds (+100 Golds bonus (total 1,100))', sku: 'BLOODSTRIKE-04', priceSell: 280 },
      { name: '2,000 Golds (+260 Golds bonus (total 2,260))', sku: 'BLOODSTRIKE-05', priceSell: 560 },
      { name: '5,000 Golds (+800 Golds bonus (total 5,800))', sku: 'BLOODSTRIKE-06', priceSell: 1393 },
    ],
  },

  {
    name: 'Racing Master',
    slug: 'racing-master',
    categorySlug: undefined,
    description: 'Racing Master top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Racing Master ราคาถูก โอนไว',
    logoUrl: `${CDN}/racing-master.jpg`,
    sortOrder: 24,
    products: [
      { name: 'Newbie Special Pack (แพ็กพิเศษสำหรับมือใหม่)', sku: 'RACINGMASTER-01', priceSell: 10 },
      { name: 'Weekly Card (บัตรรายสัปดาห์)', sku: 'RACINGMASTER-02', priceSell: 30 },
      { name: 'Growth Fund (กองทุนพัฒนา)', sku: 'RACINGMASTER-03', priceSell: 190 },
      { name: 'Special Season Contract (สัญญาซีซั่นพิเศษ)', sku: 'RACINGMASTER-04', priceSell: 279 },
      { name: '70 Gems', sku: 'RACINGMASTER-05', priceSell: 30 },
      { name: '350 Gems', sku: 'RACINGMASTER-06', priceSell: 147 },
      { name: '700 Gems', sku: 'RACINGMASTER-07', priceSell: 297 },
      { name: '1,000 Gems', sku: 'RACINGMASTER-08', priceSell: 432 },
      { name: '1,400 Gems', sku: 'RACINGMASTER-09', priceSell: 603 },
      { name: '2,100 Gems', sku: 'RACINGMASTER-10', priceSell: 900 },
      { name: '3,400 Gems', sku: 'RACINGMASTER-11', priceSell: 1431 },
      { name: '6,600 Gems', sku: 'RACINGMASTER-12', priceSell: 2781 },
    ],
  },

  {
    name: 'Marvel Rivals',
    slug: 'marvel-rivals',
    categorySlug: 'fps',
    description: 'Marvel Rivals top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Marvel Rivals ราคาถูก โอนไว',
    logoUrl: `${CDN}/marvel-rivals.jpg`,
    sortOrder: 25,
    products: [
      { name: '500 Lattices', sku: 'MARVELRIVALS-01', priceSell: 158 },
      { name: '1,000 Lattices', sku: 'MARVELRIVALS-02', priceSell: 323 },
      { name: '2,180 Lattices', sku: 'MARVELRIVALS-03', priceSell: 623 },
      { name: '5,680 Lattices', sku: 'MARVELRIVALS-04', priceSell: 1554 },
      { name: '11,680 Lattices', sku: 'MARVELRIVALS-05', priceSell: 3100 },
    ],
  },

  {
    name: 'Onmyoji Arena',
    slug: 'onmyoji-arena',
    categorySlug: 'moba',
    description: 'Onmyoji Arena top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Onmyoji Arena ราคาถูก โอนไว',
    logoUrl: `${CDN}/onmyoji-arena.jpg`,
    sortOrder: 26,
    products: [
      { name: '60 Jade', sku: 'ONMYOJIARENA-01', priceSell: 31 },
      { name: '300 Jade (Bonus 15 Jade (Total 315 Jade))', sku: 'ONMYOJIARENA-02', priceSell: 150 },
      { name: '680 Jade (Bonus 35 Jade (Total 715 Jade))', sku: 'ONMYOJIARENA-03', priceSell: 300 },
      { name: '1,280 Jade (Bonus 70 Jade (Total 1,350 Jade))', sku: 'ONMYOJIARENA-04', priceSell: 590 },
      { name: '3,280 Jade (Bonus 210 Jade (Total 3,490 Jade))', sku: 'ONMYOJIARENA-05', priceSell: 1470 },
      { name: '6,480 Jade (Bonus 420 Jade (Total 6,900 Jade))', sku: 'ONMYOJIARENA-06', priceSell: 2929 },
    ],
  },

  {
    name: 'Ace Racer',
    slug: 'ace-racer',
    categorySlug: undefined,
    description: 'Ace Racer top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Ace Racer ราคาถูก โอนไว',
    logoUrl: `${CDN}/ace-racer.jpg`,
    sortOrder: 27,
    products: [
      { name: 'Private Training', sku: 'ACERACER-01', priceSell: 585 },
      { name: '60 Tokens (Bonus 3 Tokens (Total 63 Tokens))', sku: 'ACERACER-02', priceSell: 31 },
      { name: '180 Tokens (Bonus 9 Tokens (Total 189 Tokens))', sku: 'ACERACER-03', priceSell: 92 },
      { name: '340 Tokens (Bonus 17 Tokens (Total 357 Tokens))', sku: 'ACERACER-04', priceSell: 175 },
      { name: '600 Tokens (Bonus 30 Tokens (Total 630 Tokens))', sku: 'ACERACER-05', priceSell: 310 },
      { name: '1,600 Tokens (Bonus 80 Tokens (Total 1,680 Tokens))', sku: 'ACERACER-06', priceSell: 755 },
      { name: '3,900 Tokens (Bonus 195 Tokens (Total 4,095 Tokens))', sku: 'ACERACER-07', priceSell: 1673 },
      { name: '8,000 Tokens (Bonus 400 Tokens (Total 8,400 Tokens))', sku: 'ACERACER-08', priceSell: 3229 },
    ],
  },

  {
    name: 'Identity V',
    slug: 'identity-v',
    categorySlug: undefined,
    description: 'Identity V top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Identity V ราคาถูก โอนไว',
    logoUrl: `${CDN}/identity-v.jpg`,
    sortOrder: 28,
    products: [
      { name: '60 Echoes', sku: 'IDENTITYV-01', priceSell: 30 },
      { name: '185 Echoes (Bonus 9 Echoes (Total 194 Echoes))', sku: 'IDENTITYV-02', priceSell: 89 },
      { name: '308 Echoes (Bonus 15 Echoes (Total 323 Echoes))', sku: 'IDENTITYV-03', priceSell: 149 },
      { name: '725 Echoes (Bonus 33 Echoes (Total 758 Echoes))', sku: 'IDENTITYV-04', priceSell: 349 },
      { name: '1,050 Echoes (Bonus 50 Echoes (Total 1,100 Echoes))', sku: 'IDENTITYV-05', priceSell: 497 },
      { name: '2,220 Echoes (Bonus 113 Echoes (Total 2,333 Echoes))', sku: 'IDENTITYV-06', priceSell: 984 },
      { name: '3,330 Echoes (Bonus 168 Echoes (Total 3,498 Echoes))', sku: 'IDENTITYV-07', priceSell: 1462 },
      { name: '6,660 Echoes (Bonus 340 Echoes (Total 7,000 Echoes))', sku: 'IDENTITYV-08', priceSell: 2912 },
    ],
  },

  {
    name: 'Ragnarok M: Classic',
    slug: 'ragnarok-m-classic',
    categorySlug: 'rpg',
    description: 'Ragnarok M: Classic top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Ragnarok M: Classic ราคาถูก โอนไว',
    logoUrl: `${CDN}/ragnarok-m-classic.jpg`,
    sortOrder: 29,
    products: [
      { name: 'Zeny Supply Chest x2 (Small)', sku: 'RAGNAROKMCLASS-01', priceSell: 315 },
      { name: 'Zeny Supply Chest x2 (Large)', sku: 'RAGNAROKMCLASS-02', priceSell: 945 },
      { name: 'Kafra - Upgrade Adventure Log', sku: 'RAGNAROKMCLASS-03', priceSell: 212 },
      { name: 'Kafra - Collection Adventure Log (Requires Upgrade pack purchased first)', sku: 'RAGNAROKMCLASS-04', priceSell: 720 },
      { name: '1,800,000 Zeny', sku: 'RAGNAROKMCLASS-05', priceSell: 92 },
      { name: '3,000,000 Zeny (Bonus 60,000 Zeny (Total 3,060,000 Zeny))', sku: 'RAGNAROKMCLASS-06', priceSell: 153 },
      { name: '6,800,000 Zeny (Bonus 272,000 Zeny (Total 7,072,000 Zeny))', sku: 'RAGNAROKMCLASS-07', priceSell: 315 },
      { name: '12,800,000 Zeny (Bonus 768,000 Zeny (Total 13,568,000 Zeny))', sku: 'RAGNAROKMCLASS-08', priceSell: 540 },
      { name: '32,800,000 Zeny (Bonus 2,700,000 Zeny (Total 35,500,000 Zeny))', sku: 'RAGNAROKMCLASS-09', priceSell: 1377 },
      { name: '64,800,000 Zeny (Bonus 7,200,000 Zeny (Total 72,000,000 Zeny))', sku: 'RAGNAROKMCLASS-10', priceSell: 2695 },
    ],
  },

  {
    name: 'Ragnarok Origin Global',
    slug: 'ragnarok-origin',
    categorySlug: 'rpg',
    description: 'Ragnarok Origin Global top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Ragnarok Origin Global ราคาถูก โอนไว',
    logoUrl: `${CDN}/ragnarok-origin.jpg`,
    sortOrder: 30,
    products: [
      { name: '40 Nyan Berry', sku: 'RAGNAROKORIGIN-01', priceSell: 31 },
      { name: '125 Nyan Berry', sku: 'RAGNAROKORIGIN-02', priceSell: 88 },
      { name: '210 Nyan Berry', sku: 'RAGNAROKORIGIN-03', priceSell: 146 },
      { name: '430 Nyan Berry', sku: 'RAGNAROKORIGIN-04', priceSell: 291 },
      { name: '900 Nyan Berry', sku: 'RAGNAROKORIGIN-05', priceSell: 599 },
      { name: '2,300 Nyan Berry', sku: 'RAGNAROKORIGIN-06', priceSell: 1496 },
      { name: '4,800 Nyan Berry', sku: 'RAGNAROKORIGIN-07', priceSell: 3060 },
      { name: '9,600 Nyan Berry', sku: 'RAGNAROKORIGIN-08', priceSell: 6160 },
      { name: '24,000 Nyan Berry', sku: 'RAGNAROKORIGIN-09', priceSell: 15400 },
    ],
  },

  {
    name: 'Ragnarok X: Next Generation',
    slug: 'ragnarok-x',
    categorySlug: 'rpg',
    description: 'Ragnarok X: Next Generation top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Ragnarok X: Next Generation ราคาถูก โอนไว',
    logoUrl: `${CDN}/ragnarok-x.jpg`,
    sortOrder: 31,
    products: [
      { name: 'Covenant of Encouragement', sku: 'RAGNAROKX-01', priceSell: 440 },
      { name: 'Assurance of Exclusivity', sku: 'RAGNAROKX-02', priceSell: 748 },
      { name: 'Oath of Bond', sku: 'RAGNAROKX-03', priceSell: 1215 },
      { name: '2,280 Diamonds', sku: 'RAGNAROKX-04', priceSell: 146 },
      { name: '4,550 Diamonds', sku: 'RAGNAROKX-05', priceSell: 290 },
      { name: '18,380 Diamonds', sku: 'RAGNAROKX-06', priceSell: 1180 },
      { name: '45,950 Diamonds', sku: 'RAGNAROKX-07', priceSell: 2992 },
      { name: '94,620 Diamonds', sku: 'RAGNAROKX-08', priceSell: 5984 },
    ],
  },

  {
    name: 'Ragnarok M: Eternal Love (SEA)',
    slug: 'ragnarok-m-eternal-love',
    categorySlug: 'rpg',
    description: 'Ragnarok M: Eternal Love (SEA) top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Ragnarok M: Eternal Love (SEA) ราคาถูก โอนไว',
    logoUrl: `${CDN}/ragnarok-m-eternal-love.jpg`,
    sortOrder: 32,
    products: [
      { name: 'Premium Card', sku: 'RAGNAROKMETERN-01', priceSell: 242 },
      { name: '6 Big Cat Coin (Bonus 1 Big Cat Coin (Total 7 Big Cat Coin))', sku: 'RAGNAROKMETERN-02', priceSell: 31 },
      { name: '12 Big Cat Coin (Bonus 2 Big Cat Coin (Total 14 Big Cat Coin))', sku: 'RAGNAROKMETERN-03', priceSell: 60 },
      { name: '18 Big Cat Coin (Bonus 3 Big Cat Coin (Total 21 Big Cat Coin))', sku: 'RAGNAROKMETERN-04', priceSell: 91 },
      { name: '24 Big Cat Coin (Bonus 4 Big Cat Coin (Total 28 Big Cat Coin))', sku: 'RAGNAROKMETERN-05', priceSell: 120 },
      { name: '30 Big Cat Coin (Bonus 6 Big Cat Coin (Total 36 Big Cat Coin))', sku: 'RAGNAROKMETERN-06', priceSell: 152 },
      { name: '60 Big Cat Coin (Bonus 12 Big Cat Coin (Total 72 Big Cat Coin))', sku: 'RAGNAROKMETERN-07', priceSell: 302 },
      { name: '120 Big Cat Coin (Bonus 25 Big Cat Coin (Total 145 Big Cat Coin))', sku: 'RAGNAROKMETERN-08', priceSell: 603 },
      { name: '298 Big Cat Coin (Bonus 75 Big Cat Coin (Total 373 Big Cat Coin))', sku: 'RAGNAROKMETERN-09', priceSell: 1457 },
      { name: '598 Big Cat Coin (Bonus 150 Big Cat Coin (Total 748 Big Cat Coin))', sku: 'RAGNAROKMETERN-10', priceSell: 2922 },
      { name: '1,196 Big Cat Coin (Bonus 300 Big Cat Coin (Total 1,496 Big Cat Coin))', sku: 'RAGNAROKMETERN-11', priceSell: 5835 },
      { name: '2,990 Big Cat Coin (Bonus 750 Big Cat Coin (Total 3,740 Big Cat Coin))', sku: 'RAGNAROKMETERN-12', priceSell: 14205 },
    ],
  },

  {
    name: 'Kuroko\'s Basketball: Street Rivals SEA',
    slug: 'kuroko-basketball',
    categorySlug: undefined,
    description: 'Kuroko\'s Basketball: Street Rivals SEA top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Kuroko\'s Basketball: Street Rivals SEA ราคาถูก โอนไว',
    logoUrl: `${CDN}/kuroko-basketball.jpg`,
    sortOrder: 33,
    products: [
      { name: '499 Kuroko Coupons (Bonus 20 Kuroko Coupons (Total 519 Kuroko Coupons))', sku: 'KUROKOBASKETBA-01', priceSell: 145 },
      { name: '699 Kuroko Coupons (Bonus 30 Kuroko Coupons (Total 729 Kuroko Coupons))', sku: 'KUROKOBASKETBA-02', priceSell: 205 },
      { name: '1,499 Kuroko Coupons', sku: 'KUROKOBASKETBA-03', priceSell: 437 },
      { name: '2,999 Kuroko Coupons', sku: 'KUROKOBASKETBA-04', priceSell: 760 },
      { name: '4,999 Kuroko Coupons', sku: 'KUROKOBASKETBA-05', priceSell: 1445 },
      { name: '9,999 Kuroko Coupons', sku: 'KUROKOBASKETBA-06', priceSell: 2870 },
      { name: '29,999 Kuroko Coupons', sku: 'KUROKOBASKETBA-07', priceSell: 8700 },
    ],
  },

  {
    name: 'Rainbow Six Mobile',
    slug: 'rainbow-six-mobile',
    categorySlug: 'fps',
    description: 'Rainbow Six Mobile top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Rainbow Six Mobile ราคาถูก โอนไว',
    logoUrl: `${CDN}/rainbow-six-mobile.jpg`,
    sortOrder: 34,
    products: [
      { name: '50 Platinum', sku: 'RAINBOWSIXMOBI-01', priceSell: 22 },
      { name: '110 Platinum', sku: 'RAINBOWSIXMOBI-02', priceSell: 43 },
      { name: '300 Platinum', sku: 'RAINBOWSIXMOBI-03', priceSell: 111 },
      { name: '650 Platinum', sku: 'RAINBOWSIXMOBI-04', priceSell: 215 },
      { name: '1,350 Platinum', sku: 'RAINBOWSIXMOBI-05', priceSell: 430 },
      { name: '3,500 Platinum', sku: 'RAINBOWSIXMOBI-06', priceSell: 1075 },
      { name: '7,250 Platinum', sku: 'RAINBOWSIXMOBI-07', priceSell: 2150 },
      { name: '11,250 Platinum', sku: 'RAINBOWSIXMOBI-08', priceSell: 2666 },
    ],
  },

  {
    name: 'Heartopia',
    slug: 'heartopia',
    categorySlug: undefined,
    description: 'Heartopia top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Heartopia ราคาถูก โอนไว',
    logoUrl: `${CDN}/heartopia.jpg`,
    sortOrder: 35,
    products: [
      { name: 'Golden Acorn (Basic)', sku: 'HEARTOPIA-01', priceSell: 19 },
      { name: 'Golden Acorn', sku: 'HEARTOPIA-02', priceSell: 99 },
      { name: 'Golden Acorn Gift Box', sku: 'HEARTOPIA-03', priceSell: 168 },
      { name: 'Golden Acorn Deluxe Gift Box', sku: 'HEARTOPIA-04', priceSell: 333 },
      { name: '20 Heart Diamonds', sku: 'HEARTOPIA-05', priceSell: 15 },
      { name: '60 Heart Diamonds', sku: 'HEARTOPIA-06', priceSell: 33 },
      { name: '300 Heart Diamonds (Bonus 20 Heart Diamonds)', sku: 'HEARTOPIA-07', priceSell: 168 },
      { name: '680 Heart Diamonds (Bonus 50 Heart Diamonds)', sku: 'HEARTOPIA-08', priceSell: 333 },
      { name: '1,280 Heart Diamonds (Bonus 90 Heart Diamonds)', sku: 'HEARTOPIA-09', priceSell: 645 },
      { name: '1,980 Heart Diamonds (Bonus 150 Heart Diamonds)', sku: 'HEARTOPIA-10', priceSell: 989 },
      { name: '3,280 Heart Diamonds (Bonus 270 Heart Diamonds)', sku: 'HEARTOPIA-11', priceSell: 1629 },
      { name: '6,480 Heart Diamonds (Bonus 570 Heart Diamonds)', sku: 'HEARTOPIA-12', priceSell: 3155 },
    ],
  },

  {
    name: 'Path Of Exile 2',
    slug: 'path-of-exile-2',
    categorySlug: 'rpg',
    description: 'Path Of Exile 2 top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Path Of Exile 2 ราคาถูก โอนไว',
    logoUrl: `${CDN}/path-of-exile-2.jpg`,
    sortOrder: 36,
    products: [
      { name: 'Package worth 133 THB', sku: 'PATHOFEXILE2-01', priceSell: 123 },
      { name: 'Package worth 266 THB', sku: 'PATHOFEXILE2-02', priceSell: 245 },
      { name: 'Package worth 532 THB', sku: 'PATHOFEXILE2-03', priceSell: 490 },
      { name: 'Package worth 665 THB', sku: 'PATHOFEXILE2-04', priceSell: 609 },
      { name: 'Package worth 798 THB', sku: 'PATHOFEXILE2-05', priceSell: 729 },
      { name: 'Package worth 1,463 THB', sku: 'PATHOFEXILE2-06', priceSell: 1319 },
      { name: 'Package worth 1,596 THB', sku: 'PATHOFEXILE2-07', priceSell: 1439 },
      { name: 'Package worth 1,729 THB', sku: 'PATHOFEXILE2-08', priceSell: 1559 },
      { name: 'Package worth 2,261 THB', sku: 'PATHOFEXILE2-09', priceSell: 2039 },
      { name: 'Package worth 2,394 THB', sku: 'PATHOFEXILE2-10', priceSell: 2159 },
      { name: 'Package worth 2,660 THB', sku: 'PATHOFEXILE2-11', priceSell: 2399 },
      { name: 'Package worth 3,325 THB', sku: 'PATHOFEXILE2-12', priceSell: 2989 },
      { name: 'Package worth 4,256 THB', sku: 'PATHOFEXILE2-13', priceSell: 3819 },
      { name: 'Package worth 5,453 THB', sku: 'PATHOFEXILE2-14', priceSell: 4980 },
      { name: 'Package worth 6,384 THB', sku: 'PATHOFEXILE2-15', priceSell: 5799 },
      { name: 'Package worth 11,837 THB', sku: 'PATHOFEXILE2-16', priceSell: 10600 },
      { name: 'Package worth 12,768 THB', sku: 'PATHOFEXILE2-17', priceSell: 11450 },
    ],
  },

  {
    name: 'Love And Deepspace',
    slug: 'love-and-deepspace',
    categorySlug: 'rpg',
    description: 'Love And Deepspace top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Love And Deepspace ราคาถูก โอนไว',
    logoUrl: `${CDN}/love-and-deepspace.jpg`,
    sortOrder: 37,
    products: [
      { name: 'Aurum Pass 30 Days', sku: 'LOVEANDDEEPSPA-01', priceSell: 160 },
      { name: 'Companionship Pack', sku: 'LOVEANDDEEPSPA-02', priceSell: 560 },
      { name: '300 Crystals (Bonus 30 Diamonds)', sku: 'LOVEANDDEEPSPA-03', priceSell: 160 },
      { name: '3,280 Crystals (Bonus 720 Diamonds)', sku: 'LOVEANDDEEPSPA-04', priceSell: 1592 },
      { name: '6,480 Crystals (Bonus 1,600 Diamonds)', sku: 'LOVEANDDEEPSPA-05', priceSell: 3192 },
    ],
  },

  {
    name: 'Seven Knights Re:Birth',
    slug: 'seven-knights-rebirth',
    categorySlug: 'rpg',
    description: 'Seven Knights Re:Birth top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Seven Knights Re:Birth ราคาถูก โอนไว',
    logoUrl: `${CDN}/seven-knights-rebirth.jpg`,
    sortOrder: 38,
    products: [
      { name: '27 Prisms', sku: 'SEVENKNIGHTSRE-01', priceSell: 59 },
      { name: '109 Prisms', sku: 'SEVENKNIGHTSRE-02', priceSell: 251 },
      { name: '273 Prisms', sku: 'SEVENKNIGHTSRE-03', priceSell: 610 },
      { name: '409 Prisms', sku: 'SEVENKNIGHTSRE-04', priceSell: 920 },
      { name: '718 Prisms', sku: 'SEVENKNIGHTSRE-05', priceSell: 1505 },
      { name: '990 Prisms', sku: 'SEVENKNIGHTSRE-06', priceSell: 2090 },
    ],
  },

  {
    name: 'Dragonnest M: Classic',
    slug: 'dragonnest-m-classic',
    categorySlug: 'rpg',
    description: 'Dragonnest M: Classic top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Dragonnest M: Classic ราคาถูก โอนไว',
    logoUrl: `${CDN}/dragonnest-m-classic.jpg`,
    sortOrder: 39,
    products: [
      { name: '600 Cash (Bonus 26 Cash (Total 626 Cash))', sku: 'DRAGONNESTMCLA-01', priceSell: 27 },
      { name: '3,000 Cash (Bonus 130 Cash (Total 3,130 Cash))', sku: 'DRAGONNESTMCLA-02', priceSell: 143 },
      { name: '6,000 Cash (Bonus 366 Cash (Total 6,366 Cash))', sku: 'DRAGONNESTMCLA-03', priceSell: 285 },
      { name: '12,000 Cash (Bonus 800 Cash (Total 12,800 Cash))', sku: 'DRAGONNESTMCLA-04', priceSell: 563 },
      { name: '18,000 Cash (Bonus 1,500 Cash (Total 19,500 Cash))', sku: 'DRAGONNESTMCLA-05', priceSell: 878 },
      { name: '30,000 Cash (Bonus 2,900 Cash (Total 32,900 Cash))', sku: 'DRAGONNESTMCLA-06', priceSell: 1463 },
      { name: '60,000 Cash (Bonus 6,000 Cash (Total 66,000 Cash))', sku: 'DRAGONNESTMCLA-07', priceSell: 2925 },
      { name: '120,000 Cash (Bonus 12,000 Cash (Total 132,000 Cash))', sku: 'DRAGONNESTMCLA-08', priceSell: 5775 },
      { name: '180,000 Cash (Bonus 18,000 Cash (Total 198,000 Cash))', sku: 'DRAGONNESTMCLA-09', priceSell: 8550 },
      { name: '240,000 Cash (Bonus 24,000 Cash (Total 264,000 Cash))', sku: 'DRAGONNESTMCLA-10', priceSell: 11325 },
      { name: '300,000 Cash (Bonus 30,000 Cash (Total 330,000 Cash))', sku: 'DRAGONNESTMCLA-11', priceSell: 13875 },
    ],
  },

  {
    name: 'Magic Chess: Go Go',
    slug: 'magic-chess-go-go',
    categorySlug: 'moba',
    description: 'Magic Chess: Go Go top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Magic Chess: Go Go ราคาถูก โอนไว',
    logoUrl: `${CDN}/magic-chess-go-go.jpg`,
    sortOrder: 40,
    products: [
      { name: '5 Diamonds', sku: 'MAGICCHESSGOGO-01', priceSell: 3 },
      { name: '10 Diamonds (Bonus 1 Diamond (Total 11 Diamonds))', sku: 'MAGICCHESSGOGO-02', priceSell: 6 },
      { name: '20 Diamonds (Bonus 2 Diamonds (Total 22 Diamonds))', sku: 'MAGICCHESSGOGO-03', priceSell: 11 },
      { name: '51 Diamonds (Bonus 5 Diamonds (Total 56 Diamonds))', sku: 'MAGICCHESSGOGO-04', priceSell: 28 },
      { name: '102 Diamonds (Bonus 10 Diamonds (Total 112 Diamonds))', sku: 'MAGICCHESSGOGO-05', priceSell: 57 },
      { name: '203 Diamonds (Bonus 20 Diamonds (Total 223 Diamonds))', sku: 'MAGICCHESSGOGO-06', priceSell: 107 },
      { name: '303 Diamonds (Bonus 33 Diamonds (Total 336 Diamonds))', sku: 'MAGICCHESSGOGO-07', priceSell: 170 },
      { name: '504 Diamonds (Bonus 66 Diamonds (Total 570 Diamonds))', sku: 'MAGICCHESSGOGO-08', priceSell: 277 },
      { name: '1,007 Diamonds (Bonus 156 Diamonds (Total 1,163 Diamonds))', sku: 'MAGICCHESSGOGO-09', priceSell: 552 },
      { name: '2,015 Diamonds (Bonus 383 Diamonds (Total 2,398 Diamonds))', sku: 'MAGICCHESSGOGO-10', priceSell: 1105 },
    ],
  },

  {
    name: 'Delta Force',
    slug: 'delta-force-steam',
    categorySlug: 'fps',
    description: 'Delta Force top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Delta Force ราคาถูก โอนไว',
    logoUrl: `${CDN}/delta-force-steam.jpg`,
    sortOrder: 41,
    products: [
      { name: '18 Delta Coins', sku: 'DELTAFORCESTEA-01', priceSell: 8 },
      { name: '30 Delta Coins', sku: 'DELTAFORCESTEA-02', priceSell: 15 },
      { name: '60 Delta Coins', sku: 'DELTAFORCESTEA-03', priceSell: 28 },
      { name: '300 Delta Coins (Bonus 20 Delta Coins (Total 320 Delta Coins))', sku: 'DELTAFORCESTEA-04', priceSell: 135 },
      { name: '420 Delta Coins (Bonus 40 Delta Coins (Total 460 Delta Coins))', sku: 'DELTAFORCESTEA-05', priceSell: 195 },
      { name: '680 Delta Coins (Bonus 70 Delta Coins (Total 750 Delta Coins))', sku: 'DELTAFORCESTEA-06', priceSell: 270 },
      { name: '1,280 Delta Coins (Bonus 200 Delta Coins (Total 1,480 Delta Coins))', sku: 'DELTAFORCESTEA-07', priceSell: 540 },
      { name: '1,680 Delta Coins (Bonus 300 Delta Coins (Total 1,980 Delta Coins))', sku: 'DELTAFORCESTEA-08', priceSell: 670 },
      { name: '3,280 Delta Coins (Bonus 670 Delta Coins (Total 3,950 Delta Coins))', sku: 'DELTAFORCESTEA-09', priceSell: 1299 },
      { name: '6,480 Delta Coins (Bonus 1,620 Delta Coins (Total 8,100 Delta Coins))', sku: 'DELTAFORCESTEA-10', priceSell: 2560 },
    ],
  },

  {
    name: 'AFK Journey',
    slug: 'afk-journey',
    categorySlug: 'rpg',
    description: 'AFK Journey top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม AFK Journey ราคาถูก โอนไว',
    logoUrl: `${CDN}/afk-journey.jpg`,
    sortOrder: 42,
    products: [
      { name: 'Esperia Monthly - Classic Gazette (6 Dragon Crystals)', sku: 'AFKJOURNEY-01', priceSell: 153 },
      { name: 'Esperia Monthly - Premium Gazette (22 Dragon Crystals)', sku: 'AFKJOURNEY-02', priceSell: 467 },
      { name: 'Growth Bundle (42 Dragon Crystals)', sku: 'AFKJOURNEY-03', priceSell: 936 },
      { name: '20 Dragon Crystals (1 Dragon Crystal bonus (21 total))', sku: 'AFKJOURNEY-04', priceSell: 30 },
      { name: '120 Dragon Crystals (6 Dragon Crystals bonus (126 total))', sku: 'AFKJOURNEY-05', priceSell: 153 },
      { name: '560 Dragon Crystals (28 Dragon Crystals bonus (588 total))', sku: 'AFKJOURNEY-06', priceSell: 620 },
      { name: '1,480 Dragon Crystals (74 Dragon Crystals bonus (1,554 total))', sku: 'AFKJOURNEY-07', priceSell: 1530 },
      { name: '3,000 Dragon Crystals (150 Dragon Crystals bonus (3,150 total))', sku: 'AFKJOURNEY-08', priceSell: 3145 },
    ],
  },

  {
    name: 'Overwatch 2 (Battle.net)',
    slug: 'overwatch-2',
    categorySlug: 'fps',
    description: 'Overwatch 2 (Battle.net) top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Overwatch 2 (Battle.net) ราคาถูก โอนไว',
    logoUrl: `${CDN}/overwatch-2.jpg`,
    sortOrder: 43,
    products: [
      { name: 'Invasion Bundle', sku: 'OVERWATCH2-01', priceSell: 499 },
      { name: 'Starter Pack: Season 4', sku: 'OVERWATCH2-02', priceSell: 332 },
      { name: 'Ultimate Battle Pass Bundle: Season 4', sku: 'OVERWATCH2-03', priceSell: 1329 },
      { name: 'Sojourn - Complete Mythic Weapon Skin Bundle', sku: 'OVERWATCH2-04', priceSell: 1329 },
      { name: '175 THB In-Game Pack', sku: 'OVERWATCH2-05', priceSell: 167 },
      { name: '1,749 THB In-Game Pack', sku: 'OVERWATCH2-06', priceSell: 1662 },
      { name: '3,499 THB In-Game Pack', sku: 'OVERWATCH2-07', priceSell: 3324 },
      { name: '1,399 THB In-Game Pack', sku: 'OVERWATCH2-08', priceSell: 1329 },
      { name: '1,049 THB In-Game Pack', sku: 'OVERWATCH2-09', priceSell: 997 },
      { name: '10 Mythic Prisms', sku: 'OVERWATCH2-10', priceSell: 332 },
      { name: '25 Mythic Prisms (5 Mythic Prisms bonus (30 total))', sku: 'OVERWATCH2-11', priceSell: 829 },
      { name: '40 Mythic Prisms (10 Mythic Prisms bonus (50 total))', sku: 'OVERWATCH2-12', priceSell: 1326 },
      { name: '75 Mythic Prisms (25 Mythic Prisms bonus (100 total))', sku: 'OVERWATCH2-13', priceSell: 2485 },
      { name: '500 Coins', sku: 'OVERWATCH2-14', priceSell: 167 },
      { name: '1,000 Coins', sku: 'OVERWATCH2-15', priceSell: 332 },
      { name: '2,000 Coins (200 Coins bonus (2,200 total))', sku: 'OVERWATCH2-16', priceSell: 664 },
      { name: '4,000 Coins (500 Coins bonus (4,500 total))', sku: 'OVERWATCH2-17', priceSell: 1254 },
      { name: '6,000 Coins (900 Coins bonus (6,900 total))', sku: 'OVERWATCH2-18', priceSell: 1994 },
      { name: '10,000 Coins (1,800 Coins bonus (11,800 total))', sku: 'OVERWATCH2-19', priceSell: 3324 },
    ],
  },

  {
    name: 'FC Mobile',
    slug: 'fc-mobile',
    categorySlug: undefined,
    description: 'FC Mobile top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม FC Mobile ราคาถูก โอนไว',
    logoUrl: `${CDN}/fc-mobile.jpg`,
    sortOrder: 44,
    products: [
      { name: '40 FC Points', sku: 'FCMOBILE-01', priceSell: 15 },
      { name: '100 FC Points', sku: 'FCMOBILE-02', priceSell: 35 },
      { name: '520 FC Points', sku: 'FCMOBILE-03', priceSell: 176 },
      { name: '1,070 FC Points', sku: 'FCMOBILE-04', priceSell: 342 },
      { name: '2,200 FC Points', sku: 'FCMOBILE-05', priceSell: 715 },
      { name: '5,750 FC Points', sku: 'FCMOBILE-06', priceSell: 1765 },
      { name: '12,000 FC Points', sku: 'FCMOBILE-07', priceSell: 3626 },
      { name: '99 Silver', sku: 'FCMOBILE-08', priceSell: 35 },
      { name: '499 Silver', sku: 'FCMOBILE-09', priceSell: 176 },
      { name: '999 Silver', sku: 'FCMOBILE-10', priceSell: 342 },
      { name: '1,999 Silver', sku: 'FCMOBILE-11', priceSell: 715 },
      { name: '4,999 Silver', sku: 'FCMOBILE-12', priceSell: 1765 },
      { name: '9,999 Silver', sku: 'FCMOBILE-13', priceSell: 3626 },
    ],
  },

  {
    name: 'Metal Slug: Awakening',
    slug: 'metal-slug-awakening',
    categorySlug: 'rpg',
    description: 'Metal Slug: Awakening top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Metal Slug: Awakening ราคาถูก โอนไว',
    logoUrl: `${CDN}/metal-slug-awakening.jpg`,
    sortOrder: 45,
    products: [
      { name: '60 Red Gems', sku: 'METALSLUGAWAKE-01', priceSell: 29 },
      { name: '310 Red Gems (30 Blue Gems)', sku: 'METALSLUGAWAKE-02', priceSell: 143 },
      { name: '630 Red Gems (80 Blue Gems)', sku: 'METALSLUGAWAKE-03', priceSell: 285 },
      { name: '1,300 Red Gems (200 Blue Gems)', sku: 'METALSLUGAWAKE-04', priceSell: 570 },
      { name: '3,200 Red Gems (600 Blue Gems)', sku: 'METALSLUGAWAKE-05', priceSell: 1425 },
      { name: '6,500 Red Gems (1,300 Blue Gems)', sku: 'METALSLUGAWAKE-06', priceSell: 2850 },
    ],
  },

  {
    name: 'Arena Breakout Mobile',
    slug: 'arena-breakout-mobile',
    categorySlug: 'fps',
    description: 'Arena Breakout Mobile top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Arena Breakout Mobile ราคาถูก โอนไว',
    logoUrl: `${CDN}/arena-breakout-mobile.jpg`,
    sortOrder: 46,
    products: [
      { name: 'Composite Case (6-slot storage)', sku: 'ARENABREAKOUTM-01', priceSell: 262 },
      { name: 'Advanced Battle Pass', sku: 'ARENABREAKOUTM-02', priceSell: 148 },
      { name: 'Premium Battle Pass', sku: 'ARENABREAKOUTM-03', priceSell: 437 },
      { name: '60 Bonds (6 Bonds bonus (66 total))', sku: 'ARENABREAKOUTM-04', priceSell: 31 },
      { name: '310 Bonds (25 Bonds bonus (335 total))', sku: 'ARENABREAKOUTM-05', priceSell: 148 },
      { name: '630 Bonds (45 Bonds bonus (675 total))', sku: 'ARENABREAKOUTM-06', priceSell: 293 },
      { name: '1,580 Bonds (110 Bonds bonus (1,690 total))', sku: 'ARENABREAKOUTM-07', priceSell: 733 },
      { name: '3,200 Bonds (200 Bonds bonus (3,400 total))', sku: 'ARENABREAKOUTM-08', priceSell: 1459 },
      { name: '6,500 Bonds (320 Bonds bonus (6,820 total))', sku: 'ARENABREAKOUTM-09', priceSell: 2925 },
    ],
  },

  {
    name: 'Dragon Raja',
    slug: 'dragon-raja',
    categorySlug: 'rpg',
    description: 'Dragon Raja top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Dragon Raja ราคาถูก โอนไว',
    logoUrl: `${CDN}/dragon-raja.jpg`,
    sortOrder: 47,
    products: [
      { name: 'Investment Fund (limit 1 per ID)', sku: 'DRAGONRAJA-01', priceSell: 357 },
      { name: 'Investment Fund II (limit 1 per ID)', sku: 'DRAGONRAJA-02', priceSell: 470 },
      { name: '66 Coupons', sku: 'DRAGONRAJA-03', priceSell: 27 },
      { name: '264 Coupons', sku: 'DRAGONRAJA-04', priceSell: 97 },
      { name: '1,098 Coupons', sku: 'DRAGONRAJA-05', priceSell: 366 },
      { name: '2,246 Coupons', sku: 'DRAGONRAJA-06', priceSell: 720 },
      { name: '3,768 Coupons', sku: 'DRAGONRAJA-07', priceSell: 1218 },
      { name: '7,546 Coupons', sku: 'DRAGONRAJA-08', priceSell: 2400 },
      { name: '15,092 Coupons', sku: 'DRAGONRAJA-09', priceSell: 4700 },
    ],
  },

  {
    name: 'X-HERO',
    slug: 'x-hero',
    categorySlug: 'rpg',
    description: 'X-HERO top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม X-HERO ราคาถูก โอนไว',
    logoUrl: `${CDN}/x-hero.jpg`,
    sortOrder: 48,
    products: [
      { name: '50 Tokens (2 Tokens bonus (52 total))', sku: 'XHERO-01', priceSell: 163 },
      { name: '100 Tokens (4 Tokens bonus (104 total))', sku: 'XHERO-02', priceSell: 326 },
      { name: '150 Tokens (6 Tokens bonus (156 total))', sku: 'XHERO-03', priceSell: 489 },
      { name: '200 Tokens (8 Tokens bonus (208 total))', sku: 'XHERO-04', priceSell: 652 },
      { name: '250 Tokens (10 Tokens bonus (260 total))', sku: 'XHERO-05', priceSell: 814 },
      { name: '500 Tokens (20 Tokens bonus (520 total))', sku: 'XHERO-06', priceSell: 1628 },
      { name: '1,000 Tokens (40 Tokens bonus (1,040 total))', sku: 'XHERO-07', priceSell: 3256 },
      { name: '2,000 Tokens (80 Tokens bonus (2,080 total))', sku: 'XHERO-08', priceSell: 6512 },
      { name: '4,000 Tokens (160 Tokens bonus (4,160 total))', sku: 'XHERO-09', priceSell: 13024 },
      { name: '6,000 Tokens (240 Tokens bonus (6,240 total))', sku: 'XHERO-10', priceSell: 19536 },
      { name: '10,000 Tokens (400 Tokens bonus (10,400 total))', sku: 'XHERO-11', priceSell: 32560 },
    ],
  },

  {
    name: 'Sausage Man',
    slug: 'sausage-man',
    categorySlug: 'battle-royale',
    description: 'Sausage Man top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Sausage Man ราคาถูก โอนไว',
    logoUrl: `${CDN}/sausage-man.jpg`,
    sortOrder: 49,
    products: [
      { name: '60 Candies (Extra bonus varies, shown in-game)', sku: 'SAUSAGEMAN-01', priceSell: 31 },
      { name: '300 Candies (Extra bonus varies, shown in-game)', sku: 'SAUSAGEMAN-02', priceSell: 158 },
      { name: '680 Candies (Extra bonus varies, shown in-game)', sku: 'SAUSAGEMAN-03', priceSell: 308 },
      { name: '1,280 Candies (Extra bonus varies, shown in-game)', sku: 'SAUSAGEMAN-04', priceSell: 642 },
      { name: '1,980 Candies (Extra bonus varies, shown in-game)', sku: 'SAUSAGEMAN-05', priceSell: 968 },
      { name: '3,280 Candies (Extra bonus varies, shown in-game)', sku: 'SAUSAGEMAN-06', priceSell: 1584 },
      { name: '6,480 Candies (Extra bonus varies, shown in-game)', sku: 'SAUSAGEMAN-07', priceSell: 3256 },
    ],
  },

  {
    name: 'MU Origin 3',
    slug: 'mu-origin-3',
    categorySlug: 'rpg',
    description: 'MU Origin 3 top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม MU Origin 3 ราคาถูก โอนไว',
    logoUrl: `${CDN}/mu-origin-3.jpg`,
    sortOrder: 50,
    products: [
      { name: '350 Sacred Diamonds', sku: 'MUORIGIN3-01', priceSell: 162 },
      { name: '1,050 Sacred Diamonds', sku: 'MUORIGIN3-02', priceSell: 495 },
      { name: '2,100 Sacred Diamonds', sku: 'MUORIGIN3-03', priceSell: 990 },
      { name: '3,500 Sacred Diamonds', sku: 'MUORIGIN3-04', priceSell: 1620 },
      { name: '7,000 Sacred Diamonds', sku: 'MUORIGIN3-05', priceSell: 3330 },
      { name: '10,500 Sacred Diamonds', sku: 'MUORIGIN3-06', priceSell: 4950 },
      { name: '14,000 Sacred Diamonds', sku: 'MUORIGIN3-07', priceSell: 6480 },
      { name: '21,000 Sacred Diamonds', sku: 'MUORIGIN3-08', priceSell: 9810 },
    ],
  },

  {
    name: 'ZEPETO',
    slug: 'zepeto',
    categorySlug: undefined,
    description: 'ZEPETO top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม ZEPETO ราคาถูก โอนไว',
    logoUrl: `${CDN}/zepeto.jpg`,
    sortOrder: 51,
    products: [
      { name: '7 ZEMS', sku: 'ZEPETO-01', priceSell: 13 },
      { name: '14 ZEMS', sku: 'ZEPETO-02', priceSell: 23 },
      { name: '28 ZEMS', sku: 'ZEPETO-03', priceSell: 45 },
      { name: '58 ZEMS', sku: 'ZEPETO-04', priceSell: 89 },
      { name: '128 ZEMS', sku: 'ZEPETO-05', priceSell: 194 },
      { name: '323 ZEMS', sku: 'ZEPETO-06', priceSell: 487 },
      { name: '1,000 ZEMS', sku: 'ZEPETO-07', priceSell: 1457 },
      { name: '4,680 Coins', sku: 'ZEPETO-08', priceSell: 23 },
      { name: '9,600 Coins', sku: 'ZEPETO-09', priceSell: 45 },
      { name: '25,200 Coins', sku: 'ZEPETO-10', priceSell: 111 },
      { name: '40,700 Coins', sku: 'ZEPETO-11', priceSell: 177 },
      { name: '110,000 Coins', sku: 'ZEPETO-12', priceSell: 471 },
      { name: '300,000 Coins', sku: 'ZEPETO-13', priceSell: 1257 },
    ],
  },

  {
    name: 'Super Sus',
    slug: 'super-sus',
    categorySlug: undefined,
    description: 'Super Sus top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Super Sus ราคาถูก โอนไว',
    logoUrl: `${CDN}/super-sus.jpg`,
    sortOrder: 52,
    products: [
      { name: 'Weekly Card', sku: 'SUPERSUS-01', priceSell: 29 },
      { name: 'Monthly Card', sku: 'SUPERSUS-02', priceSell: 289 },
      { name: 'Super Pass', sku: 'SUPERSUS-03', priceSell: 144 },
      { name: 'Super Pass Bundle', sku: 'SUPERSUS-04', priceSell: 275 },
      { name: 'Super VIP Card', sku: 'SUPERSUS-05', priceSell: 332 },
      { name: '100 Goldstar', sku: 'SUPERSUS-06', priceSell: 22 },
      { name: '310 Goldstar', sku: 'SUPERSUS-07', priceSell: 64 },
      { name: '520 Goldstar', sku: 'SUPERSUS-08', priceSell: 107 },
      { name: '1,060 Goldstar', sku: 'SUPERSUS-09', priceSell: 216 },
      { name: '2,180 Goldstar', sku: 'SUPERSUS-10', priceSell: 444 },
      { name: '5,600 Goldstar', sku: 'SUPERSUS-11', priceSell: 1135 },
    ],
  },

  {
    name: 'Roblox Gift Card',
    slug: 'roblox-gift-card',
    categorySlug: 'gift-cards',
    description: 'Roblox Gift Card top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Roblox Gift Card ราคาถูก โอนไว',
    logoUrl: `${CDN}/roblox-gift-card.jpg`,
    sortOrder: 53,
    products: [
      { name: '300 THB card', sku: 'ROBLOXGIFTCARD-01', priceSell: 285 },
      { name: '750 THB card', sku: 'ROBLOXGIFTCARD-02', priceSell: 713 },
    ],
  },

  {
    name: 'Steam Gift Card',
    slug: 'steam-gift-card',
    categorySlug: 'gift-cards',
    description: 'Steam Gift Card top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Steam Gift Card ราคาถูก โอนไว',
    logoUrl: `${CDN}/steam-gift-card.jpg`,
    sortOrder: 54,
    products: [
      { name: '50 THB card', sku: 'STEAMGIFTCARD-01', priceSell: 50 },
      { name: '100 THB card', sku: 'STEAMGIFTCARD-02', priceSell: 99 },
      { name: '200 THB card', sku: 'STEAMGIFTCARD-03', priceSell: 198 },
      { name: '350 THB card', sku: 'STEAMGIFTCARD-04', priceSell: 347 },
      { name: '1,000 THB card', sku: 'STEAMGIFTCARD-05', priceSell: 990 },
    ],
  },

  {
    name: 'Riot Card',
    slug: 'riot-card',
    categorySlug: 'gift-cards',
    description: 'Riot Card top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม Riot Card ราคาถูก โอนไว',
    logoUrl: `${CDN}/riot-card.jpg`,
    sortOrder: 55,
    products: [
      { name: '139 THB card', sku: 'RIOTCARD-01', priceSell: 131 },
      { name: '279 THB card', sku: 'RIOTCARD-02', priceSell: 263 },
      { name: '559 THB card', sku: 'RIOTCARD-03', priceSell: 526 },
      { name: '979 THB card', sku: 'RIOTCARD-04', priceSell: 920 },
      { name: '1,400 THB card', sku: 'RIOTCARD-05', priceSell: 1316 },
      { name: '2,800 THB card', sku: 'RIOTCARD-06', priceSell: 2632 },
    ],
  },

  {
    name: '@Cash Gift Card',
    slug: 'at-cash-gift-card',
    categorySlug: 'gift-cards',
    description: '@Cash Gift Card top-up, sourced from getmoneythailand.com.',
    descriptionTh: 'เติมเกม @Cash Gift Card ราคาถูก โอนไว',
    logoUrl: `${CDN}/at-cash-gift-card.jpg`,
    sortOrder: 56,
    products: [
      { name: '55 THB card', sku: 'ATCASHGIFTCARD-01', priceSell: 54 },
      { name: '89 THB card', sku: 'ATCASHGIFTCARD-02', priceSell: 88 },
      { name: '189 THB card', sku: 'ATCASHGIFTCARD-03', priceSell: 187 },
      { name: '245 THB card', sku: 'ATCASHGIFTCARD-04', priceSell: 243 },
      { name: '349 THB card', sku: 'ATCASHGIFTCARD-05', priceSell: 346 },
      { name: '450 THB card', sku: 'ATCASHGIFTCARD-06', priceSell: 446 },
      { name: '888 THB card', sku: 'ATCASHGIFTCARD-07', priceSell: 880 },
    ],
  },
];

async function main() {
  const categoryIdBySlug = new Map<string, string>();
  for (const cat of CATEGORIES) {
    const dbCategory = await prisma.category.upsert({
      where: { slug: cat.slug },
      create: cat,
      update: cat,
    });
    categoryIdBySlug.set(cat.slug, dbCategory.id);
    console.log(`✓ category ${dbCategory.name}`);
  }

  for (const game of GAMES) {
    const { products, requiresServer, categorySlug, ...gameData } = game;
    const categoryId = categorySlug ? categoryIdBySlug.get(categorySlug) : undefined;

    const dbGame = await prisma.game.upsert({
      where: { slug: game.slug },
      create: { ...gameData, categoryId, isActive: true },
      update: { ...gameData, categoryId },
    });

    for (const [index, product] of products.entries()) {
      const priceCost = Math.round(product.priceSell * COST_RATIO * 100) / 100;
      const data = {
        gameId: dbGame.id,
        name: product.name,
        sku: product.sku,
        priceCost,
        priceSell: product.priceSell,
        requiresServer: requiresServer ?? false,
        sortOrder: index + 1,
        isActive: true,
      };
      await prisma.gameProduct.upsert({
        where: { sku: product.sku },
        create: data,
        update: data,
      });
    }

    console.log(`✓ ${game.name} — ${products.length} products`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
