FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package.json turbo.json ./
COPY apps/api/package.json ./apps/api/
RUN npm install
COPY apps/api ./apps/api
WORKDIR /app/apps/api
RUN npx prisma generate
CMD ["npm", "run", "start:dev"]
